-- Task 46: Supabase 기반 관리자 DB 및 로깅 시스템 구축
-- SQL 스키마 (Supabase SQL Editor에서 실행)

-- 1. Detection Logs: 유해 표현 감지 이력
create table public.detection_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text_content text not null,           -- 감지된 텍스트
  confidence float not null,            -- AI 신뢰도 (0.0 ~ 1.0)
  threshold_used float not null,        -- 당시 적용된 임계값
  model_version text,                   -- 사용된 모델 (koelectra/kanana)
  is_harmful boolean default true,      -- 유해 여부
  filter_mode text default 'ocr',       -- 필터 모드 (ocr | voice 등)
  user_id uuid default null,            -- (선택) 요청한 사용자 ID
  metadata jsonb default '{}'::jsonb    -- 추가 정보 (IP, 클라이언트 버전 등)
);

-- 2. App Settings: 서버 설정 원격 관리
create table public.app_settings (
  key text primary key,                 -- 예: 'threshold_koelectra'
  value text not null,                  -- 예: '0.5'
  description text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 초기 설정값 주입
insert into public.app_settings (key, value, description) values
('threshold_koelectra', '0.5', 'KoElectra 모델 민감도 임계값'),
('threshold_kanana', '0.22', 'Kanana 모델 민감도 임계값');

-- 3. RLS (Row Level Security) 설정
alter table public.detection_logs enable row level security;
alter table public.app_settings enable row level security;

-- 정책: 서비스 롤(FastAPI 서버)은 모든 권한, 인증된 사용자(관리자)는 조회 권한
create policy "Server Service Role Full Access" on public.detection_logs
  for all using (true) with check (true);

-- 모든 사용자(익명 포함)가 조회 가능하도록 변경
create policy "Public Read Only" on public.detection_logs
  for select using (true);

create policy "Authenticated Admins Update Settings" on public.app_settings
  for update to authenticated using (true);

-- user_feedback 테이블도 RLS 활성화
alter table public.user_feedback enable row level security;

-- 모든 사용자(익명 포함)가 user_feedback을 조회/작성 가능
create policy "Public Read Feedback" on public.user_feedback
  for select using (true);

create policy "Public Insert Feedback" on public.user_feedback
  for insert with check (true);

-- 4. 인덱스 추가 (검색 성능 향상)
create index idx_detection_logs_created_at on public.detection_logs(created_at desc);
create index idx_detection_logs_is_harmful on public.detection_logs(is_harmful);

-- 5. User Feedback: 사용자 피드백 수집 테이블
create table public.user_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid,                         -- ✅ 추가됨 (Supabase User ID 또는 Device UUID)
  category text default 'general',
  content text not null,
  contact_email text,
  status text default 'new',
  metadata jsonb default '{}'::jsonb
);


